version: "2"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  identical-code:
    config:
      threshold: 4
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 80
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 10
plugins: 
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - "javascript"
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      extensions:
        - .html
        - .js
      ignore_warnings: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - ToDo
      - Todo
      - TO-DO
      - To-Do
      - HACK
      - Hack
      - HERE BE DRAGONS
      - Here Be Dragons
  grep:
    enabled: true
    config:
      patterns:
        bad-merge:
          pattern: <<<<<<<|>>>>>>>
          annotation: "Bad merge"
          severity: critical
          categories: ["Bug Risk", "Performance"]
          content: >
            Bad merge detected by one or more of the following strings of the form: "<<<<<<< Updated upstream", ">>>>>>> Stashed changes". In all likelihood, this will result in syntax errors when attempting to run your application.
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
      MD033:
        enabled: false
    config:
      line-length: false
  nodesecurity:
    enabled: true
exclude_patterns:
  - "bin/"
  - "coverage/"
  - "node_modules/"
  - "test/"
