env:
  global:
    - CC_TEST_REPORTER_ID=a21956e14247505ab97820b5d61c9656f8c0459287a7091798375468cc10e403
language: node_js
node_js:
  - "8.6"
  - "12.8"
sudo: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - cp coverage/mocha/lcov.info coverage/lcov.info
after_success:
  - ./cc-test-reporter after-build -t lcov
